[package]
name = "bevy_animation_graph_book"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_animation_graph = { git = "https://github.com/mbrea-c/bevy_animation_graph.git", default-features = false }
bevy_animation_graph_editor = { git = "https://github.com/mbrea-c/bevy_animation_graph.git", default-features = false }
bevy_ahoy = "0.1.0-rc.6"
bevy_enhanced_input = "0.24.1"
avian3d = { version = "0.6.0-rc.1", default-features = false, features = [
    "parry-f32",
    "3d",
    "f32",
    "debug-plugin",
] }
